// Bundles src/worker/worker.ts into a standalone classic worker script.
// Output:
//   src/worker/generated/WorkerSource.ts — the script as a string, inlined as a blob: URL by spawnWorker()
//   src/worker/generated/konfeti.worker.js — the same script, published as `konfeti/konfeti.worker.js` for CSP setups
// Both files are generated (git-ignored); every script that compiles the library runs this first.

import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { rolldown } from "rolldown";

const root = fileURLToPath(new URL("../", import.meta.url));
const outDir = `${root}src/worker/generated/`;

const bundle = await rolldown({
  input: `${root}src/worker/worker.ts`,
  platform: "browser",
  logLevel: "warn",
  transform: { target: "es2022" },
});
const { output } = await bundle.generate({ format: "iife", minify: true });
const code = output[0].code;

mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}konfeti.worker.js`, code);
writeFileSync(
  `${outDir}WorkerSource.ts`,
  `// generated by scripts/build-worker.mjs — do not edit\n` +
    `/**\n * Bundled Worker Script.\n */\n` +
    `export const WORKER_SOURCE: string = ${JSON.stringify(code)};\n`,
);

console.log(`build-worker: ${(code.length / 1024).toFixed(1)} kB worker script`);
