/**
 * Initial Control Values of the v1 Editor, Frozen.
 * Only the keys the v1 → v2 link migration reshapes or fills in. A v1 link left out every value at its v1 initial,
 * so the migration starts from these to show what the sender saw. They are a copy of the v1 control table
 * (`304f6b1`, `playground/src/controls.ts`) and must never follow the current one.
 */
export const V1_INITIALS = {
  velocityMin: 1000,
  velocityMax: 1800,
  lifetime: 3200,
  lifetimeJitter: 0.15,
  originX: 0.5,
  originSpreadX: 0,
  angle: 90,
  originY: 0.6,
  formationFont: "900 110px sans-serif",
  formationWidth: 420,
  formationVelocityMin: 300,
  formationVelocityMax: 700,
  widthMin: 6,
  widthMax: 10,
  heightMin: 10,
  heightMax: 16,
  aspectRatio: 1.6,
  cornerRadius: 0,
  skew: 0,
  gradientA: "#ff5e7e",
  gradientB: "#26ccff",
  gradientAngle: 45,
  strokeWidth: 1,
  opacity: 1,
  scale: 1,
  rotationMax: 360,
  rotationSpeed: 240,
  flipFrequency: 1.2,
  wobbleAmplitude: 8,
  wobbleFrequency: 0.8,
  tilt: 0,
  scaleEasing: "easeInQuad",
  // v1 always sent the shadow color opaque, also when the sender never touched it
  shadowColor: "#000000",
  shadowBlur: 6,
  shadowY: 3,
  trailWidth: 3,
  gravity: 700,
  drag: 3.5,
  wind: 0,
  swirlStrength: 200,
  swirlFrequency: 0.6,
  attractTarget: "pointer",
  attractStrength: 900,
  "star.size": 16,
  "triangle.size": 12,
  "polygon.size": 12,
  "heart.size": 16,
  "path.size": 18,
  "emoji.size": 24,
  "text.size": 18,
  "image.size": 24,
  "sprite.size": 26,
  "star.points": 5,
  "polygon.sides": 6,
  "ribbon.length": 30,
  "ribbon.waves": 2,
  "path.viewBox": 24,
  "sprite.fps": 12,
  "star.colors": [],
  "heart.colors": ["#ff3d7f", "#ff8fb1", "#e0115f"],
  "text.fontFamily": "Inter, system-ui, sans-serif",
} as const;
